platform :ios, '13.0'
use_frameworks!

target 'FetchedResultsController_Example' do
  pod 'FetchedResultsController', :path => '../'
  
  target 'FetchedResultsController_Tests' do
    inherit! :search_paths
    
  end
end
