use_frameworks!

platform :ios, '12.4'

target 'GenericResultsController_Example' do
  pod 'GenericResultsController', :path => '../'

  target 'GenericResultsController_Tests' do
    inherit! :search_paths

    
  end
end
